apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vote_app.deployment.name }}
  labels:
    name: {{ .Values.vote_app.deployment.name }} 
    app: {{ include "lib.name" . }}
spec:
  replicas: {{ .Values.vote_app.deployment.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.vote_app.deployment.labels_name }}
      app: {{ .Values.vote_app.deployment.labels_app }}
    
  template:
    metadata:
      name: {{ .Values.vote_app.deployment.labels_name }}
      labels:
        name: {{ .Values.vote_app.deployment.labels_name }}
        app: {{ include "lib.name" . }}
    spec:
      imagePullSecrets:
      - name: vote
      containers:
      - name: voting-app
        image: {{ .Values.vote_app.deployment.image }}:{{ .Values.vote_app.deployment.tag }}
        # Resource Start         
        {{- if .Values.vote_app.deployment.resources }}
        resources:
          {{- if .Values.vote_app.deployment.resources.requests }}
          requests:
            memory: {{ .Values.vote_app.deployment.resources.requests.memory | default "50Mi" | quote }}
            cpu: {{ .Values.vote_app.deployment.resources.requests.cpu | default "10m" | quote }}
          {{- else}}
          requests:
            memory: "50Mi"
            cpu: "10m"
          {{- end}}
          {{- if .Values.vote_app.deployment.resources.limits }}
          limits:
            memory: {{ .Values.vote_app.deployment.resources.limits.memory | default "1024Mi" | quote }}
            cpu: {{ .Values.vote_app.deployment.resources.limits.cpu | default "1" | quote }}
          {{- else}}  
          limits:
            memory: "1024Mi"
            cpu: "1"
          {{- end }}
        {{- else }}
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "1024Mi"
            cpu: "1"          
        {{- end}}
        # Resource End                 
        ports:
        - containerPort: {{ .Values.vote_app.deployment.port }} 
