apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vote_app.service.name }}
  labels:
    name: {{ .Values.vote_app.service.name }}
    app: {{ include "lib.name" . }}
spec:
  # type:  {{ .Values.vote_app.service.type }}
  {{- if eq .Values.vote_app.service.type "NodePort" }}
  type: ClusterIP
  {{- end }}
  ports:
    - port:  {{ .Values.vote_app.service.port }}
      targetPort: {{ .Values.vote_app.service.targetPort }}
  selector:
    name:  {{ .Values.vote_app.deployment.labels_name }} 
    app: {{ include "lib.name" . }}