apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vote_app.deployment.name }}
  labels:
    name: {{ .Values.vote_app.deployment.name }} 
    app: demo-voting-app
spec:
  replicas: {{ .Values.vote_app.deployment.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.vote_app.deployment.labels_name }}
      app: {{ .Values.vote_app.deployment.labels_app }}
    
  template:
    metadata:
      name: {{ .Values.vote_app.deployment.labels_name }}
      labels:
        name: {{ .Values.vote_app.deployment.labels_name }}
        app: demo-voting-app
    spec:
      imagePullSecrets:
      - name: vote
      containers:
      - name: voting-app
        image: devendradhoot/vote:latest
        ports:
        - containerPort: {{ .Values.vote_app.deployment.port }} 
