apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    name: worker-app-deploy
    app: {{ include "lib.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: {{ include "lib.name" . }}
    
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: {{ include "lib.name" . }}
    spec:
      containers:
        - name: worker-app
          image: devendradhoot/worker:latest
          imagePullPolicy: IfNotPresent         
